#!/bin/sh

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

echo "REPO_ROOT=$REPO_ROOT"
ls "$REPO_ROOT/utils"

PYTHON="python"

echo "📷 Génération du CHANGELOG..."

"$PYTHON" "$REPO_ROOT/utils/generate_changelog.py"
"$PYTHON" "$REPO_ROOT/utils/export.py"

git add CHANGELOG.md README.md

echo "✅ OK"